export const DOMINICAN_SOURCES = [
  {
    id: "datos-gob-do",
    name: "Portal Nacional de Datos Abiertos / datos.gob.do",
    institution: "Gobierno de la República Dominicana",
    section: "data_sources",
    category: "open_data",
    sourceType: "ckan",
    url: "https://datos.gob.do",
    status: "active",
    strategicValue: "high",
    bccRelevance: ["national discovery layer", "public datasets", "institution mapping"],
    connectorKey: "ckan_datos_gob_do",
    notes: "National discovery layer for public datasets, institutions and resources."
  },
  {
    id: "api-gob-do",
    name: "Portal de APIs del Estado Dominicano",
    institution: "Gobierno de la República Dominicana",
    section: "data_sources",
    category: "government_api",
    sourceType: "web_portal",
    url: "https://api.gob.do",
    status: "unknown",
    strategicValue: "medium",
    bccRelevance: ["future government APIs", "source monitoring"],
    connectorKey: "",
    notes: "Monitor for future government APIs; not treated as the primary source."
  },
  {
    id: "dgcp-datacompras",
    name: "DGCP / DataCompras RD",
    institution: "Dirección General de Contrataciones Públicas",
    section: "public_market",
    category: "procurement",
    sourceType: "web_portal",
    url: "https://www.dgcp.gob.do",
    status: "partial",
    strategicValue: "high",
    bccRelevance: ["public procurement", "tenders", "contracts", "suppliers", "public price intelligence"],
    connectorKey: "dgcp_discovery",
    notes: "Public procurement, tenders, contracts, suppliers, buying units and public price intelligence."
  },
  {
    id: "bcrd",
    name: "Banco Central de la República Dominicana",
    institution: "Banco Central de la República Dominicana",
    section: "economy_finance",
    category: "economy",
    sourceType: "web_portal",
    url: "https://www.bancentral.gov.do",
    status: "planned",
    strategicValue: "medium",
    bccRelevance: ["macroeconomic indicators", "exchange rates", "inflation", "tourism", "external sector"],
    connectorKey: "bcrd",
    notes: "Connector skeleton in place; live indicator sync is not enabled yet."
  },
  {
    id: "sib",
    name: "Superintendencia de Bancos",
    institution: "Superintendencia de Bancos",
    section: "economy_finance",
    category: "finance",
    sourceType: "api",
    url: "https://sb.gob.do",
    status: "planned",
    strategicValue: "medium",
    bccRelevance: ["financial system statistics", "banking context"],
    connectorKey: "sib",
    notes: "Connector skeleton in place; live financial statistic sync is not enabled yet."
  },
  {
    id: "one",
    name: "Oficina Nacional de Estadística / ONE",
    institution: "Oficina Nacional de Estadística",
    section: "demographics_statistics",
    category: "statistics",
    sourceType: "web_portal",
    url: "https://www.one.gob.do",
    status: "partial",
    strategicValue: "medium",
    bccRelevance: ["population", "education", "poverty", "services", "mobility", "social indicators"],
    connectorKey: "",
    notes: "Statistical source registry support; dataset ingestion comes mainly from CKAN discovery in this MVP."
  },
  {
    id: "geoportal-one",
    name: "Geoportal ONE",
    institution: "Oficina Nacional de Estadística",
    section: "territory_environment",
    category: "geospatial",
    sourceType: "web_portal",
    url: "https://geoportal.one.gob.do",
    status: "planned",
    strategicValue: "medium",
    bccRelevance: ["geostatistics", "territorial demographic context"],
    connectorKey: "",
    notes: "Planned source for geostatistical visualization and territorial demographic context."
  },
  {
    id: "iderd-geoportal",
    name: "IDERD / Geoportal",
    institution: "Infraestructura de Datos Espaciales de la República Dominicana",
    section: "territory_environment",
    category: "geospatial",
    sourceType: "csw",
    url: "https://www.iderd.gob.do",
    status: "partial",
    strategicValue: "medium",
    bccRelevance: ["official geospatial layers", "OGC services", "administrative boundaries", "infrastructure layers"],
    connectorKey: "iderd_metadata",
    notes: "Metadata-level connector registers service structure; no full map in this MVP."
  },
  {
    id: "aduanas",
    name: "Dirección General de Aduanas",
    institution: "Dirección General de Aduanas",
    section: "economy_finance",
    category: "trade",
    sourceType: "web_portal",
    url: "https://www.aduanas.gob.do",
    status: "planned",
    strategicValue: "medium",
    bccRelevance: ["imports", "exports", "trade agreements", "industrial signals"],
    connectorKey: "",
    notes: "Trade intelligence source registered; connector is planned."
  },
  {
    id: "environment-open-data",
    name: "Environmental datasets / national open data",
    institution: "Gobierno de la República Dominicana",
    section: "territory_environment",
    category: "environment",
    sourceType: "ckan",
    url: "https://datos.gob.do",
    status: "partial",
    strategicValue: "medium",
    bccRelevance: ["air quality", "water", "protected areas", "forest fires", "environmental risk"],
    connectorKey: "ckan_datos_gob_do",
    notes: "Environment datasets discovered through the national CKAN catalog."
  },
  {
    id: "openaq",
    name: "OpenAQ",
    institution: "OpenAQ",
    section: "territory_environment",
    category: "environment",
    sourceType: "api",
    url: "https://openaq.org",
    status: "planned",
    strategicValue: "low",
    bccRelevance: ["air quality", "environmental context"],
    connectorKey: "",
    notes: "Global air quality API; Dominican coverage may vary."
  },
  {
    id: "nasa-earthdata",
    name: "NASA Earthdata",
    institution: "NASA",
    section: "territory_environment",
    category: "satellite",
    sourceType: "satellite_api",
    url: "https://www.earthdata.nasa.gov",
    status: "planned",
    strategicValue: "medium",
    bccRelevance: ["Earth observation", "climate", "fire", "vegetation", "water", "environmental signals"],
    connectorKey: "",
    notes: "Satellite source registered; deep processing is not part of this MVP."
  },
  {
    id: "copernicus",
    name: "Copernicus Data Space",
    institution: "European Space Agency / European Union",
    section: "territory_environment",
    category: "satellite",
    sourceType: "satellite_api",
    url: "https://dataspace.copernicus.eu",
    status: "planned",
    strategicValue: "medium",
    bccRelevance: ["Sentinel satellite data", "STAC", "openEO", "Sentinel Hub", "OGC services"],
    connectorKey: "",
    notes: "Satellite source registered; deep processing is not part of this MVP."
  }
];

export const CURATED_INSTITUTIONS = [
  { id: "micm", name: "Ministerio de Industria, Comercio y Mipymes", kind: "ministry", sector: "Industry and commerce", sourceId: "api-gob-do", relevanceToBCC: "high", notes: "Industrial programs, SMEs, innovation and manufacturing signals." },
  { id: "mescyt", name: "Ministerio de Educación Superior, Ciencia y Tecnología", kind: "ministry", sector: "Science and higher education", sourceId: "api-gob-do", relevanceToBCC: "high", notes: "Research, universities, grants and scientific capacity." },
  { id: "msp", name: "Ministerio de Salud Pública", kind: "ministry", sector: "Health", sourceId: "api-gob-do", relevanceToBCC: "medium", notes: "Diagnostics, laboratory and health system signals." },
  { id: "ambiente", name: "Ministerio de Medio Ambiente", kind: "ministry", sector: "Environment", sourceId: "api-gob-do", relevanceToBCC: "medium", notes: "Water, protected areas and environmental monitoring context." },
  { id: "dgcp", name: "Dirección General de Contrataciones Públicas", kind: "agency", sector: "Procurement", sourceId: "dgcp-datacompras", relevanceToBCC: "high", notes: "Core source for tenders, contracts and public demand." },
  { id: "one-inst", name: "Oficina Nacional de Estadística", kind: "agency", sector: "Statistics", sourceId: "one", relevanceToBCC: "medium", notes: "Population, social and economic datasets." },
  { id: "indocal", name: "Instituto Dominicano para la Calidad", kind: "agency", sector: "Quality infrastructure", sourceId: "datos-gob-do", relevanceToBCC: "high", notes: "Metrology, calibration and standards proximity." },
  { id: "iibi", name: "Instituto de Innovación en Biotecnología e Industria", kind: "agency", sector: "Biotech and industry", sourceId: "datos-gob-do", relevanceToBCC: "high", notes: "Biotechnology, laboratory and industrial research proximity." },
  { id: "uasd", name: "Universidad Autónoma de Santo Domingo", kind: "university", sector: "Higher education", sourceId: "one", relevanceToBCC: "medium", notes: "Research and academic partnership channel." },
  { id: "intec", name: "Instituto Tecnológico de Santo Domingo", kind: "university", sector: "Higher education", sourceId: "one", relevanceToBCC: "high", notes: "Engineering, science and innovation partnership channel." },
  { id: "santiago", name: "Ayuntamiento de Santiago", kind: "municipality", sector: "Municipal government", sourceId: "geoportal-one", relevanceToBCC: "medium", notes: "Smart city and territorial modernization signals." },
  { id: "edesur", name: "Edesur Dominicana", kind: "public_company", sector: "Electricity distribution", sourceId: "dgcp-datacompras", relevanceToBCC: "medium", notes: "Infrastructure and public company procurement context." },
  { id: "iadb", name: "Banco Interamericano de Desarrollo", kind: "international", sector: "Development finance", sourceId: "api-gob-do", relevanceToBCC: "medium", notes: "Development projects, modernization and funding signals." }
];

export function sourceById(id) {
  return DOMINICAN_SOURCES.find(source => source.id === id) || null;
}
