create table if not exists public.intelligence_api_clients (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  token_hash text not null,
  token_prefix text not null default '',
  scopes text[] not null default array['intelligence:read']::text[],
  enabled boolean not null default true,
  rate_limit_per_minute integer not null default 60,
  daily_limit integer not null default 5000,
  expires_at timestamptz,
  last_used_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint intelligence_api_clients_name_check check (char_length(btrim(name)) between 1 and 120),
  constraint intelligence_api_clients_token_hash_check check (token_hash ~ '^[a-f0-9]{64}$'),
  constraint intelligence_api_clients_token_prefix_check check (char_length(token_prefix) <= 32),
  constraint intelligence_api_clients_scopes_check check (
    coalesce(array_length(scopes, 1), 0) between 1 and 16
    and scopes <@ array['intelligence:read']::text[]
  ),
  constraint intelligence_api_clients_rate_limit_check check (rate_limit_per_minute between 1 and 1000),
  constraint intelligence_api_clients_daily_limit_check check (daily_limit between 1 and 1000000)
);
create unique index if not exists intelligence_api_clients_name_uidx on public.intelligence_api_clients (lower(name));
create unique index if not exists intelligence_api_clients_token_hash_uidx on public.intelligence_api_clients (token_hash);
create index if not exists intelligence_api_clients_enabled_idx on public.intelligence_api_clients (enabled, expires_at);
create table if not exists public.intelligence_api_audit (
  id bigint generated by default as identity primary key,
  client_id uuid references public.intelligence_api_clients(id) on delete set null,
  operation text not null,
  query_hash text not null default '',
  filters jsonb not null default '{}'::jsonb,
  result_count integer not null default 0,
  duration_ms integer not null default 0,
  status_code integer not null,
  created_at timestamptz not null default now(),
  constraint intelligence_api_audit_operation_check check (char_length(btrim(operation)) between 1 and 80),
  constraint intelligence_api_audit_query_hash_check check (query_hash = '' or query_hash ~ '^[a-f0-9]{64}$'),
  constraint intelligence_api_audit_filters_check check (jsonb_typeof(filters) = 'object'),
  constraint intelligence_api_audit_result_count_check check (result_count >= 0),
  constraint intelligence_api_audit_duration_check check (duration_ms >= 0),
  constraint intelligence_api_audit_status_check check (status_code between 100 and 599)
);
create index if not exists intelligence_api_audit_client_created_idx on public.intelligence_api_audit (client_id, created_at desc);
create index if not exists intelligence_api_audit_created_idx on public.intelligence_api_audit (created_at desc);
alter table public.intelligence_api_clients enable row level security;
alter table public.intelligence_api_audit enable row level security;
revoke all on public.intelligence_api_clients from public, anon, authenticated;
revoke all on public.intelligence_api_audit from public, anon, authenticated;
revoke all on sequence public.intelligence_api_audit_id_seq from public, anon, authenticated;
grant all on public.intelligence_api_clients to service_role;
grant all on public.intelligence_api_audit to service_role;
grant usage, select on sequence public.intelligence_api_audit_id_seq to service_role;
comment on table public.intelligence_api_clients is 'Backend-only application credentials for read-only BCC Intelligence consumers. Plaintext tokens are never stored.';
comment on table public.intelligence_api_audit is 'Backend-only audit trail for BCC Intelligence API access. Stores operation metadata, not full prompts or source content.';;
